Currency converter branch
hebaali9/currency-converter pull request #4
Opened 2023-01-03 18:19 UTC by hebaali9

2023-01-06 12:50 UTC, SirajKakeh requested changes

2023-01-06 12:50 UTC, SirajKakeh commented on src/App.css
> +} */
let's keep the `box-sizing: border-box;` property

2023-01-06 12:50 UTC, SirajKakeh commented on src/App.css
> +  align-items: center;
let's remove unused comments

2023-01-06 12:50 UTC, SirajKakeh commented on src/App.tsx
> +};
this seems like a global type related to the store, let's define in the store and export it from there. It seems like the wrong place to define it here

2023-01-06 12:50 UTC, SirajKakeh commented on src/App.tsx
> +        <Link to="/currenctPage">
the route should be user-friendly. Let's name it something more user friendly

2023-01-06 12:50 UTC, SirajKakeh commented on src/currencyPage.tsx
> +          //onChange={(e) => setFromAmount(Number(e.target.value))}
unused comment

2023-01-06 12:50 UTC, SirajKakeh commented on src/currencyPage.tsx
> +          // @ts-ignore
no need to ignore the error here, let's fix it instead

2023-01-06 12:50 UTC, SirajKakeh commented on src/main.tsx
> +  <Provider store={store}>
let's keep React.StrictMode and nest `Provider` inside it

2023-01-06 12:50 UTC, SirajKakeh commented on src/protectedRoutes.tsx
> +  };
same as above, let's move `RootState` definition to store files

2023-01-06 12:50 UTC, SirajKakeh commented on src/protectedRoutes.tsx
> +  const token = useSelector((state: RootState) => state.token);
this selector is used in many places, let's define `useToken` function that does the same thing and use it everywhere we want to access the token

2023-01-06 19:52 UTC, hebaali9 commented on src/App.css
> +  align-items: center;
it is not unused i was trying to make a navbar

2023-01-06 20:11 UTC, hebaali9 commented on src/App.css
> +} */
Ma fhemtak please wade7

2023-01-07 19:49 UTC, hebaali9 commented
اعمل ميرج؟؟؟

2023-01-08 11:51 UTC, merged